version: '3.8'

services:
  mediawiki:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./images:/var/www/html/images
      - ./skins:/var/www/html/skins
      - ./LocalSettings.php:/var/www/html/LocalSettings.php
    environment:
      - MEDIAWIKI_DB_TYPE=mysql
      - MEDIAWIKI_DB_HOST=db
      - MEDIAWIKI_DB_USER=wikiuser
      - MEDIAWIKI_DB_PASSWORD=secret
      - MEDIAWIKI_DB_NAME=wikidb
      - WIKI_ENV=dev
    depends_on:
      - db

  db:
    image: mariadb:10.5
    restart: always
    environment:
      - MYSQL_DATABASE=wikidb
      - MYSQL_USER=wikiuser
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=rootpass
    volumes:
      - db_data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - db

volumes:
  db_data:
