<?php
# This file was automatically generated by the MediaWiki 1.45 installer.
# Manual changes are allowed here.
# See includes/MainConfigSchema.php for all configurable settings.

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}

##
## Basic Site Settings
##
$wgSitename = "ויקישבע"; // Wiki name
$wgScriptPath = ""; // URL base path (empty = root)
$wgArticlePath = "/$1"; // Pretty URLs
$wgMetaNamespace = 'ויקישבע'; // Project namespace name

## Resource Paths
$wgResourceBasePath = $wgScriptPath;

##
## Database Settings
##
$wgDBtype = "mysql";
$wgDBserver   = getenv('MEDIAWIKI_DB_HOST'); // DB server via ENV
$wgDBname     = getenv('MEDIAWIKI_DB_NAME'); // DB name via ENV
$wgDBuser     = getenv('MEDIAWIKI_DB_USER'); // DB user via ENV
$wgDBpassword = getenv('MEDIAWIKI_DB_PASSWORD'); // DB password via ENV

# MySQL specific options
$wgDBprefix = "";
$wgDBssl = false; // Consider enabling SSL for production database connections
$wgDBTableOptions = "ENGINE=InnoDB, DEFAULT CHARSET=binary";

##
## Email Settings
##
$wgEnableEmail = true;
$wgEnableUserEmail = true; // Allow users to send emails to each other
$wgEmergencyContact = "info@wiki7.co.il"; // System email contact
$wgPasswordSender = "info@wiki7.co.il"; // Email sender address
$wgEnotifUserTalk = false; // Email notification when talkpage changes
$wgEnotifWatchlist = false; // Email notification for watchlist changes
$wgEmailAuthentication = true; // Require email confirmation

##
## Upload Settings
##
$wgEnableUploads = true;
$wgUseImageMagick = true;
$wgImageMagickConvertCommand = "/usr/bin/convert";

# InstantCommons allows using images from Wikimedia Commons
$wgUseInstantCommons = false; // Set to true if you want to use Wikimedia Commons images

##
## Language and Localization
##
$wgLanguageCode = "he"; // Hebrew
$wgLocaltimezone = "Asia/Jerusalem"; // Server timezone
$wgWiki7EnableHEFonts = true; // Enable Hebrew fonts

##
## Security Settings
##
$wgSecretKey = getenv('WG_SECRET_KEY') ?: 'dev-only-secret-key-replace-in-production';
$wgAuthenticationTokenVersion = "1";
$wgUpgradeKey = getenv('WG_UPGRADE_KEY') ?: 'dev-only-upgrade'; // Upgrade key for web installer

##
## Cache Settings
##
$wgMainCacheType = CACHE_ACCEL;
$wgMemCachedServers = [];

##
## Rights and Permissions
##
$wgGroupPermissions["*"]["edit"] = false; // Prevent anonymous edits

##
## Skins
##
wfLoadSkin( 'Vector' );
wfLoadSkin( 'Citizen' );
wfLoadSkin( 'Wiki7' );

$wgDefaultSkin = 'Wiki7';

// Wiki7 skin configuration
$wgWiki7HeaderPosition = 'left'; // Auto-flips to right in RTL

// Drawer footer community links
$wgWiki7DrawerFooterLinks = [
    [ 'label' => 'פייסבוק', 'href' => 'https://www.facebook.com/HapoelBeerSheva', 'icon' => 'logo-Facebook', 'external' => true ],
    [ 'label' => 'טוויטר / X', 'href' => 'https://twitter.com/HapoelBeerSheva', 'icon' => 'logo-X', 'external' => true ],
    [ 'label' => 'אינסטגרם', 'href' => 'https://www.instagram.com/hapoelbeersheva/', 'icon' => 'logo-Instagram', 'external' => true ],
    [ 'label' => 'יוטיוב', 'href' => 'https://www.youtube.com/@HapoelBeerSheva', 'icon' => 'logo-YouTube', 'external' => true ],
    [ 'label' => 'האתר הרשמי', 'href' => 'https://www.hapoelbs.co.il', 'icon' => 'linkExternal', 'external' => true ],
];

// Main page configuration
$wgMainPageIsDomainRoot = true; // Serve main page at domain root

##
## Extensions
##
wfLoadExtension( 'CategoryTree' );
wfLoadExtension( 'Cite' );
wfLoadExtension( 'ConfirmEdit' );
wfLoadExtension( 'Echo' );
wfLoadExtension( 'LoginNotify' );
wfLoadExtension( 'ParserFunctions' );
wfLoadExtension( 'Scribunto' );
wfLoadExtension( 'SyntaxHighlight_GeSHi' );
wfLoadExtension( 'TemplateData' );
wfLoadExtension( 'Thanks' );
wfLoadExtension( 'VisualEditor' );
wfLoadExtension( 'WikiEditor' );

wfLoadExtension( 'Cargo' );
wfLoadExtension( 'PageForms' );
wfLoadExtension( 'TabberNeue' );

# SEO — Description2 extracts a meta `description` page property from each article's
# leading paragraph; the BeforePageDisplay hook further down reads that property and
# emits the full OG/Twitter Card/canonical-link surface. We do the emission ourselves
# (rather than via OpenGraphMeta) because:
#   - OpenGraphMeta emits og:title = the bare page title (often <20 chars on a fan
#     wiki); OG previews want 50-60 chars. We append a tagline.
#   - OpenGraphMeta does not emit Twitter Card tags at all.
#   - The main page is template-only, so Description2 finds no leading paragraph to
#     extract from. We need a site-wide fallback description.
#   - OpenGraphMeta defaults og:image to the SVG logo, which most platforms reject.
#     We point at a proper 1200×630 PNG.
wfLoadExtension( 'Description2' );
$wgEnableMetaDescriptionFunctions = true; // expose {{#description2:}} for explicit overrides
$wgEnableCanonicalServerLink = true;       // <link rel="canonical"> on every page

$wgWiki7Tagline             = 'אנציקלופדיית הפועל באר שבע';
$wgWiki7FallbackDescription = 'אנציקלופדיית הפועל באר שבע — היסטוריה, שחקנים, גביעים, אגדות ואוהדים.';
$wgWiki7ShareImage          = 'https://wiki7.co.il/assets/social-share.png';

$wgHooks['BeforePageDisplay'][] = function ( OutputPage $out, Skin $skin ) {
    global $wgWiki7Tagline, $wgWiki7FallbackDescription, $wgWiki7ShareImage, $wgSitename;

    // Description: prefer Description2's value (set during the parser phase);
    // fall back to the site-wide tagline-style sentence when empty.
    $description = $out->getProperty( 'description' );
    if ( empty( $description ) ) {
        $description = $wgWiki7FallbackDescription;
    }
    // OG / Twitter want short summaries; truncate to ~200 chars so providers don't trim awkwardly.
    if ( mb_strlen( $description ) > 200 ) {
        $description = rtrim( mb_substr( $description, 0, 197 ) ) . '…';
    }

    // og:title — augment the bare page title with the tagline so previews carry brand
    // context. The page H1 / MediaWiki page title itself is unaffected.
    $pageTitle = $out->getTitle()->getText();
    $ogTitle   = $pageTitle . ' - ' . $wgWiki7Tagline;

    $canonicalUrl = $out->getTitle()->getCanonicalURL();
    $ogType       = $out->getTitle()->isMainPage() ? 'website' : 'article';

    // MediaWiki's $out->addMeta() only emits `<meta name="...">`. OG tags need
    // `<meta property="...">`, so we render head items as raw HTML.
    $esc = static function ( $s ) {
        return htmlspecialchars( $s, ENT_QUOTES, 'UTF-8' );
    };
    $tags = [
        // Generic
        [ 'name',     'description',       $description ],
        // Open Graph (Facebook, WhatsApp, LinkedIn, Slack, Discord, …)
        [ 'property', 'og:title',          $ogTitle ],
        [ 'property', 'og:description',    $description ],
        [ 'property', 'og:type',           $ogType ],
        [ 'property', 'og:url',            $canonicalUrl ],
        [ 'property', 'og:site_name',      $wgSitename ],
        [ 'property', 'og:locale',         'he_IL' ],
        [ 'property', 'og:image',          $wgWiki7ShareImage ],
        [ 'property', 'og:image:type',     'image/png' ],
        [ 'property', 'og:image:width',    '1200' ],
        [ 'property', 'og:image:height',   '630' ],
        // Twitter Card (Twitter/X) — large image variant
        [ 'name',     'twitter:card',         'summary_large_image' ],
        [ 'name',     'twitter:title',        $ogTitle ],
        [ 'name',     'twitter:description',  $description ],
        [ 'name',     'twitter:image',        $wgWiki7ShareImage ],
    ];
    foreach ( $tags as $tag ) {
        [ $attr, $key, $value ] = $tag;
        $id = 'wiki7-meta-' . $attr . '-' . str_replace( ':', '-', $key );
        $out->addHeadItem(
            $id,
            "\t<meta {$attr}=\"" . $esc( $key ) . "\" content=\"" . $esc( $value ) . "\">\n"
        );
    }
};

##
## Logo
##
$wgLogos = [
	'1x' => "$wgResourceBasePath/assets/logo-white.svg",
	'icon' => "$wgResourceBasePath/assets/logo-white.svg",
];

##
## Monitoring
##
$wgPingback = true; // Help MediaWiki devs by sending anonymous usage stats

##
## Environment-specific settings
##
# Switches behavior based on WIKI_ENV ("production" vs "development")

if ( getenv('WIKI_ENV') === 'production' ) {
    // Production mode
    $wgServer = "https://wiki7.co.il";
    $wgCanonicalServer = "https://wiki7.co.il";
    $wgCookieSecure = true; // Only transmit cookies over HTTPS
    
    // Error handling
    $wgShowExceptionDetails = false; // Hide internal error details for security
    $wgDebugToolbar = false; // Should be false in production for security
    
    // Caching settings
    $wgCachePages = true; // Enable page caching
    $wgEnableParserCache = true; // Enable parsed output cache
    if ( getenv( 'REDIS_HOST' ) ) {
        // Sidecar Redis container — shared across all PHP workers (unlike APCu,
        // which is per-process). Big speedup on ParserOutput hits because every
        // worker reuses the same parsed page tree.
        $wgObjectCaches['redis'] = [
            'class'      => 'RedisBagOStuff',
            'servers'    => [ getenv( 'REDIS_HOST' ) . ':6379' ],
            'persistent' => true,
        ];
        $wgMainCacheType    = 'redis';
        $wgParserCacheType  = 'redis';
        $wgMessageCacheType = 'redis';
        $wgSessionCacheType = 'redis';
    } else {
        // Fallback for environments without Redis available.
        $wgMainCacheType   = CACHE_ACCEL;
        $wgParserCacheType = CACHE_ACCEL;
    }
    $wgCacheDirectory = "/tmp"; // Use local tmp dir for cache if needed
    
    // Resource paths
    $wgLoadScript = 'https://wiki7.co.il/load.php';
    $wgExtensionAssetsPath = 'https://wiki7.co.il/extensions';
    $wgResourceBasePath = $wgScriptPath;
    
    // Logging
    $wgDebugLogGroups['FileOperation'] = 'php://stderr'; // Log file operations to stderr
    
    // S3 for file storage - this requires AWS extension to be installed
    if (getenv('S3_BUCKET_NAME')) {
        # Load AWS extension
        wfLoadExtension( 'AWS' );

        # Credentials come from the EC2 instance role via IMDSv2 (no explicit $wgAWSCredentials).
        # The AWS SDK PHP credential provider chain auto-discovers in this order:
        #   ECS task role → EC2 instance metadata → env vars → ~/.aws/credentials
        # Override only if explicit access keys are present in the environment (e.g. local dev).
        if (getenv('AWS_ACCESS_KEY_ID') && getenv('AWS_SECRET_ACCESS_KEY')) {
            $wgAWSCredentials = [
                'key'    => getenv('AWS_ACCESS_KEY_ID'),
                'secret' => getenv('AWS_SECRET_ACCESS_KEY'),
                'token'  => false,
            ];
        }

        # S3 configuration
        $wgAWSRegion = 'il-central-1';
        $wgAWSBucketName = getenv('S3_BUCKET_NAME');
        
        # This is the key setting that fixes the regional endpoint issue
        # It tells MediaWiki to serve files through your CloudFront/custom domain
        $wgAWSBucketDomain = 'https://wiki7.co.il';

        # Subdirectory within the bucket where files are stored
        $wgAWSBucketTopSubdirectory = "/images";
        
        # Set paths for direct S3 access (fallback if CloudFront is unavailable)
        $wgUploadPath = 'https://' . $wgAWSBucketName . '.s3.il-central-1.amazonaws.com/images';

        # You can add CloudWatch logging for S3 operations if needed
        # $wgAWSLogging = true;
    } else {
        # Fall back to local file system if S3 bucket name is not provided
        $wgUploadDirectory = '/var/www/html/images';
        $wgUploadPath = 'https://wiki7.co.il/images';
        $wgStylePath = 'https://wiki7.co.il/skins';
    }
} else {
    // Development mode
    $wgServer = "http://localhost:8080";
    
    // Error handling - verbose in development
    $wgShowExceptionDetails = true; // Show full error stack traces
    $wgShowDBErrorBacktrace = true; // Show DB error backtraces
    $wgDebugToolbar = true; // Enable debug toolbar in UI
    $wgDevelopmentWarnings = true; // Show PHP notices
    
    // Caching - disabled in development for easier debugging
    $wgCachePages = false; // Disable page caching for live changes
    $wgEnableParserCache = false; // Disable parsed output cache
    $wgMainCacheType = CACHE_NONE; // No object caching
    $wgParserCacheType = CACHE_NONE;
    $wgCacheDirectory = false; // Disable file cache
    
    // Logging
    $wgDebugLogFile = "/tmp/mediawiki-debug.log"; // Log debug to file
    
    // Local file storage in development
    $wgUploadDirectory = '/var/www/html/images';
    $wgUploadPath = '/images';

    // Resource loader debug
    $wgResourceLoaderDebug = true;
}

# --- End of environment-specific settings ---