<?php
# This file was automatically generated by the MediaWiki 1.45 installer.
# Manual changes are allowed here.
# See includes/MainConfigSchema.php for all configurable settings.

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}

##
## Basic Site Settings
##
$wgSitename = "ויקישבע"; // Wiki name
$wgScriptPath = ""; // URL base path (empty = root)
$wgArticlePath = "/$1"; // Pretty URLs
$wgMetaNamespace = 'ויקישבע'; // Project namespace name

## Resource Paths
$wgResourceBasePath = $wgScriptPath;

##
## Database Settings
##
$wgDBtype = "mysql";
$wgDBserver   = getenv('MEDIAWIKI_DB_HOST'); // DB server via ENV
$wgDBname     = getenv('MEDIAWIKI_DB_NAME'); // DB name via ENV
$wgDBuser     = getenv('MEDIAWIKI_DB_USER'); // DB user via ENV
$wgDBpassword = getenv('MEDIAWIKI_DB_PASSWORD'); // DB password via ENV

# MySQL specific options
$wgDBprefix = "";
$wgDBssl = false; // Consider enabling SSL for production database connections
$wgDBTableOptions = "ENGINE=InnoDB, DEFAULT CHARSET=binary";

##
## Email Settings
##
$wgEnableEmail = true;
$wgEnableUserEmail = true; // Allow users to send emails to each other
$wgEmergencyContact = "info@wiki7.co.il"; // System email contact
$wgPasswordSender = "info@wiki7.co.il"; // Email sender address
$wgEnotifUserTalk = false; // Email notification when talkpage changes
$wgEnotifWatchlist = false; // Email notification for watchlist changes
$wgEmailAuthentication = true; // Require email confirmation

##
## Upload Settings
##
$wgEnableUploads = true;
$wgUseImageMagick = true;
$wgImageMagickConvertCommand = "/usr/bin/convert";

# InstantCommons allows using images from Wikimedia Commons
$wgUseInstantCommons = false; // Set to true if you want to use Wikimedia Commons images

##
## Language and Localization
##
$wgLanguageCode = "he"; // Hebrew
$wgLocaltimezone = "Asia/Jerusalem"; // Server timezone
$wgWiki7EnableHEFonts = true; // Enable Hebrew fonts

##
## Security Settings
##
$wgSecretKey = getenv('WG_SECRET_KEY') ?: 'dev-only-secret-key-replace-in-production';
$wgAuthenticationTokenVersion = "1";
$wgUpgradeKey = getenv('WG_UPGRADE_KEY') ?: 'dev-only-upgrade'; // Upgrade key for web installer

##
## Cache Settings
##
$wgMainCacheType = CACHE_ACCEL;
$wgMemCachedServers = [];

##
## Job queue — drained out-of-band, not inline on web requests
##
# Inline runs (the default $wgJobRunRate = 1) bolt one job onto every web hit,
# adding latency to whichever unlucky user triggered the page; behind CloudFront
# the origin sees few hits to begin with, so refreshLinks / Cargo population
# drains slowly. We disable inline runs entirely and rely on a host-side cron
# that calls runJobs.php every minute (UserData in compute-stack.ts).
$wgJobRunRate = 0;

##
## Rights and Permissions
##
$wgGroupPermissions["*"]["edit"] = false; // Prevent anonymous edits

##
## Skins
##
wfLoadSkin( 'Vector' );
wfLoadSkin( 'Citizen' );
wfLoadSkin( 'Wiki7' );

$wgDefaultSkin = 'Wiki7';

// Wiki7 skin configuration
$wgWiki7HeaderPosition = 'left'; // Auto-flips to right in RTL

// Drawer footer community links
$wgWiki7DrawerFooterLinks = [
    [ 'label' => 'פייסבוק', 'href' => 'https://www.facebook.com/HapoelBeerSheva', 'icon' => 'logo-Facebook', 'external' => true ],
    [ 'label' => 'טוויטר / X', 'href' => 'https://twitter.com/HapoelBeerSheva', 'icon' => 'logo-X', 'external' => true ],
    [ 'label' => 'אינסטגרם', 'href' => 'https://www.instagram.com/hapoelbeersheva/', 'icon' => 'logo-Instagram', 'external' => true ],
    [ 'label' => 'יוטיוב', 'href' => 'https://www.youtube.com/@HapoelBeerSheva', 'icon' => 'logo-YouTube', 'external' => true ],
    [ 'label' => 'האתר הרשמי', 'href' => 'https://www.hapoelbs.co.il', 'icon' => 'linkExternal', 'external' => true ],
];

// Main page configuration
$wgMainPageIsDomainRoot = true; // Serve main page at domain root

##
## Extensions
##
wfLoadExtension( 'CategoryTree' );
wfLoadExtension( 'Cite' );
wfLoadExtension( 'ConfirmEdit' );
wfLoadExtension( 'Echo' );
wfLoadExtension( 'LoginNotify' );
wfLoadExtension( 'ParserFunctions' );
wfLoadExtension( 'Scribunto' );
wfLoadExtension( 'SyntaxHighlight_GeSHi' );
wfLoadExtension( 'TemplateData' );
wfLoadExtension( 'Thanks' );
wfLoadExtension( 'VisualEditor' );
wfLoadExtension( 'WikiEditor' );

wfLoadExtension( 'Cargo' );
wfLoadExtension( 'PageForms' );
wfLoadExtension( 'TabberNeue' );

# === SEO ============================================================================
# Two extensions cooperate:
#   - Description2 extracts a per-page <meta name="description"> from the article's
#     leading paragraph. WikiSEO reads its output when present.
#   - WikiSEO emits the full OG + Twitter Card + Schema.org JSON-LD + canonical-link
#     surface. Per-page customisation is via the {{#seo:...}} parser function in
#     wikitext. The site-wide defaults below cover everything not page-specific.
#
# Per-page customisation example (used by Cargo templates once Phase 3 content lands):
#   {{#seo:
#     |title=שי אליאס - פרופיל שחקן
#     |title_mode=replace
#     |description=שחקן הפועל באר שבע מאז 2018, רגל ימין דומיננטית, ...
#     |image=ShayElias.jpg
#     |image_alt=שי אליאס בעונת 2024/25
#     |type=Person
#     |published_time=2018-08-15
#   }}
# WikiSEO emits the matching og:*, twitter:*, and Schema.org JSON-LD blocks. For
# SportsTeam / SportsEvent / Person, set |type= and WikiSEO maps to the correct
# Schema.org type.
wfLoadExtension( 'Description2' );
wfLoadExtension( 'WikiSEO' );
$wgEnableMetaDescriptionFunctions = true; // expose {{#description2:}} for explicit overrides

# Site-wide SEO defaults
$wgEnableCanonicalServerLink = true;                      // <link rel="canonical"> everywhere
# og:image needs a fully-qualified URL - the OG spec requires it and most social platforms
# silently drop relative refs. We hardcode the prod URL because this config block runs
# BEFORE the environment-specific block where $wgServer is set; the file is anyway production-
# only meaningful (dev/localhost URLs aren't socially shared).
$wgWikiSeoDefaultImage       = 'https://wiki7.co.il/assets/social-share.png'; // 1200x630 PNG, CDK->S3->CF
$wgTwitterCardType           = 'summary_large_image';      // Use the large preview variant
# Organization.logo / Article.image fallback for Schema.org is fed by adding a PNG entry
# to $wgLogos below (next to the SVG entries) - WikiSEO filters $wgLogos by extension and
# rejects SVG. Setting $wgLogo (singular) wouldn't help here because getWikiLogo only
# falls back to it when $wgLogos is unset.

# Site-wide WikiSEO metadata defaults. The WikiSEOPreAddMetadata hook fires before
# WikiSEO's OG/Twitter/Schema.org generators emit tags; we fill in missing keys so the
# default behaviour is brand-forward, og:type is correct, and og:locale is he_IL.
# Per-page {{#seo:...}} calls still win - we only set keys that weren't already provided.
$wgWiki7Tagline = 'אנציקלופדיית הפועל באר שבע';
$wgHooks['WikiSEOPreAddMetadata'][] = function ( array &$metadata ) {
    global $wgWiki7Tagline, $wgSitename;

    // og:title - we want the brand name "ויקישבע" to appear on every share preview, on
    // every page. Different patterns per page type:
    //   - Main page: "ויקישבע - אנציקלופדיית הפועל באר שבע" (brand first, then descriptive
    //     tagline; the bare page title "עמוד ראשי" alone is bland).
    //   - Article pages: "<page name> - ויקישבע" (standard SEO pattern, page-specific
    //     identifier first, site brand at the end).
    //
    // WikiSEO's title_mode='append' looks like it should do this but it doesn't - it only
    // affects the HTML <title> element, NOT og:title. The OG generator's title-emission
    // path is:
    //   1) addTitleMeta() emits og:title using $out->getTitle()->getPrefixedText()
    //   2) the generator's foreach loop then EMITS og:title AGAIN from metadata['title']
    //      via addHeadItem with the same key, overwriting step 1
    // So step-2 wins, and og:title ends up equal to whatever metadata['title'] holds. To
    // produce the brand-inclusive titles above we build the full string ourselves and
    // hand it to WikiSEO via metadata['title'] with title_mode='replace'.
    if ( !isset( $metadata['title'] ) ) {
        $title         = \RequestContext::getMain()->getTitle();
        $pageTitleText = $title ? $title->getPrefixedText() : '';

        if ( $title && $title->isMainPage() ) {
            $metadata['title'] = $wgSitename . ' - ' . $wgWiki7Tagline;
        } elseif ( $pageTitleText !== '' ) {
            $metadata['title'] = $pageTitleText . ' - ' . $wgSitename;
        } else {
            $metadata['title'] = $wgSitename;
        }
        $metadata['title_mode'] = 'replace';
    }

    // og:type - 'website' on the main page, 'article' everywhere else. RequestContext is
    // the supported way to reach the current title from a hook that only receives metadata.
    if ( !isset( $metadata['type'] ) ) {
        $title = \RequestContext::getMain()->getTitle();
        $metadata['type'] = ( $title && $title->isMainPage() ) ? 'website' : 'article';
    }

    // og:locale - Hebrew Israel; matches $wgLanguageCode='he' and the RTL skin direction.
    if ( !isset( $metadata['locale'] ) ) {
        $metadata['locale'] = 'he_IL';
    }
};

# Fallback description for pages where neither Description2 (no leading paragraph) nor
# a {{#seo:description=...}} call produced one - most commonly the main page, whose
# wikitext is template-only. The hook idempotently skips when something else already
# emitted a description, so per-page descriptions always win when they exist.
$wgWiki7FallbackDescription = 'אנציקלופדיית הפועל באר שבע - היסטוריה, שחקנים, גביעים ואוהדים';
$wgHooks['BeforePageDisplay'][] = function ( OutputPage $out, Skin $skin ) {
    global $wgWiki7FallbackDescription;
    foreach ( $out->getHeadItemsArray() as $item ) {
        // Skip the fallback if WikiSEO / Description2 / a manual <meta> already set one.
        if ( preg_match( '/(name|property)="(description|og:description)"/i', $item ) ) {
            return;
        }
    }
    $esc = htmlspecialchars( $wgWiki7FallbackDescription, ENT_QUOTES, 'UTF-8' );
    $out->addHeadItem( 'wiki7-fallback-description',
          "\t<meta name=\"description\" content=\"{$esc}\">\n"
        . "\t<meta property=\"og:description\" content=\"{$esc}\">\n"
        . "\t<meta name=\"twitter:description\" content=\"{$esc}\">\n" );
};

##
## Logo
##
$wgLogos = [
	'1x' => "$wgResourceBasePath/assets/logo-white.svg",
	'icon' => "$wgResourceBasePath/assets/logo-white.svg",
	// WikiSEO's Schema.org generator reads $wgLogos for the Organization.logo and
	// Article.image fallbacks (Generator/AbstractBaseGenerator::getWikiLogo). It
	// filters by extension and ONLY accepts jpg/jpeg/png/gif/webp; SVG is rejected,
	// so the SVG entries above were producing empty arrays in the JSON-LD output.
	// The 'wikiseo' key isn't read by the skin (it pulls '1x' and 'icon' only); it
	// exists so the Schema.org generator finds a real bitmap URL to emit.
	'wikiseo' => 'https://wiki7.co.il/assets/social-share.png',
];

##
## Favicon + Apple touch icon
##
# Browser tab, bookmark icon, and iOS/Android home screen. Modern browsers prefer the SVG
# variant (crisp at every tab DPI, ~7 KB) and fall back to the multi-resolution ICO. iOS
# uses the 180x180 PNG for home-screen bookmarks. All three assets are generated from the
# same brand-red + white-logo recipe as social-share.png.
#
# - $wgFavicon emits the legacy <link rel="shortcut icon"> for older browsers.
# - The BeforePageDisplay hook adds the modern <link rel="icon" type="image/svg+xml"> and
#   the <link rel="apple-touch-icon"> tags, both of which MW core doesn't emit.
# - The Dockerfile also copies favicon.ico to /var/www/html/favicon.ico for tools that
#   auto-fetch /favicon.ico without parsing the HTML (bookmark scrapers, RSS readers,
#   link-preview generators).
$wgFavicon = '/assets/favicon.ico';

$wgHooks['BeforePageDisplay'][] = function ( OutputPage $out, Skin $skin ) {
	global $wgSitename, $wgWiki7Tagline;

	$out->addLink( [
		'rel'  => 'icon',
		'type' => 'image/svg+xml',
		'href' => '/assets/favicon.svg',
	] );
	$out->addLink( [
		'rel'   => 'apple-touch-icon',
		'href'  => '/assets/apple-touch-icon.png',
		'sizes' => '180x180',
	] );

	// Force-set the HTML <title> to match og:title. WikiSEO's modifyPageTitle runs BEFORE
	// the WikiSEOPreAddMetadata hook fires, so the title we put into metadata['title']
	// via that hook never reaches modifyPageTitle - it returns early on the missing key
	// and the bare default <title> (just $wgSitename on the main page, or "<page> - <site>"
	// elsewhere) leaks through. Setting the HTML title ourselves at BeforePageDisplay
	// time fires AFTER WikiSEO's hook completes and BEFORE the skin reads getHTMLTitle
	// to compose the <title> element, so the value sticks.
	//
	// Per-page {{#seo:title=...}} overrides still win: that parser-function call writes
	// the 'title' value to the page_props table, modifyPageTitle reads it from there and
	// calls setHTMLTitle BEFORE our hook runs, and we detect the page-prop and skip our
	// force-set so we don't clobber the editor's choice.
	$title = $out->getTitle();
	if ( !$title ) {
		return;
	}
	$pageProps = \MediaWiki\MediaWikiServices::getInstance()->getPageProps();
	$customTitleProp = $pageProps->getProperties( $title, 'title' );
	if ( !empty( $customTitleProp ) ) {
		return;
	}
	$htmlTitle = $title->isMainPage()
		? $wgSitename . ' - ' . $wgWiki7Tagline
		: $title->getPrefixedText() . ' - ' . $wgSitename;
	$out->setHTMLTitle( $htmlTitle );
};

##
## Monitoring
##
$wgPingback = true; // Help MediaWiki devs by sending anonymous usage stats

##
## Environment-specific settings
##
# Switches behavior based on WIKI_ENV ("production" vs "development")

if ( getenv('WIKI_ENV') === 'production' ) {
    // Production mode
    $wgServer = "https://wiki7.co.il";
    $wgCanonicalServer = "https://wiki7.co.il";
    $wgCookieSecure = true; // Only transmit cookies over HTTPS

    // === CDN awareness =====================================================================
    // $wgUseCdn = true makes MW emit s-maxage Cache-Control directives so CloudFront actually
    // caches HTML pages at the edge (without it MW emits s-maxage=0 and every page miss
    // becomes an origin hit).
    $wgUseCdn = true;

    // Real client IP recovery behind CloudFront. CloudFront's origin request policy
    // (ALL_VIEWER_AND_CLOUDFRONT_2022, set in cloudfront-stack.ts) adds the
    // 'CloudFront-Viewer-Address' header. CloudFront populates it from the actual TCP
    // viewer connection and strips any client-supplied value, so it cannot be spoofed.
    //
    // We overwrite $_SERVER['REMOTE_ADDR'] BEFORE MW boots: MW core reads REMOTE_ADDR
    // directly in WebRequest::getIP() and only consults X-Forwarded-For when REMOTE_ADDR
    // is a trusted proxy (per $wgCdnServersNoPurge). Setting REMOTE_ADDR to the real viewer
    // IP makes RecentChanges, IP blocks, and abuse throttling work correctly without
    // having to track CloudFront's dynamic IP ranges in $wgCdnServersNoPurge.
    //
    // Format from CloudFront docs: "<ip>:<port>" for IPv4, "<ip>:<port>" with the IP in
    // square brackets for IPv6 ("[2001:db8::1]:443"). We strip the port and the brackets.
    if ( !empty( $_SERVER['HTTP_CLOUDFRONT_VIEWER_ADDRESS'] ) ) {
        $cfViewer = $_SERVER['HTTP_CLOUDFRONT_VIEWER_ADDRESS'];
        if ( $cfViewer[0] === '[' ) {
            // IPv6: "[2001:db8::1]:443" -> "2001:db8::1"
            $end = strpos( $cfViewer, ']' );
            if ( $end !== false ) {
                $_SERVER['REMOTE_ADDR'] = substr( $cfViewer, 1, $end - 1 );
            }
        } else {
            // IPv4: "1.2.3.4:56789" -> "1.2.3.4"
            $colon = strrpos( $cfViewer, ':' );
            $_SERVER['REMOTE_ADDR'] = $colon !== false
                ? substr( $cfViewer, 0, $colon )
                : $cfViewer;
        }
    }
    // Deliberately NOT setting $wgCdnServersNoPurge: CloudFront's edge IP ranges are
    // dynamic (the AmazonIpSpaceChanged SNS topic publishes updates) and hard-coding a
    // snapshot would silently rot. Since we override REMOTE_ADDR above, MW never needs
    // to walk XFF, so the trusted-proxy list isn't load-bearing here.
    
    // Error handling
    $wgShowExceptionDetails = false; // Hide internal error details for security
    $wgDebugToolbar = false; // Should be false in production for security
    
    // Caching settings
    $wgCachePages = true; // Enable page caching
    $wgEnableParserCache = true; // Enable parsed output cache
    if ( getenv( 'REDIS_HOST' ) ) {
        // Sidecar Redis container - shared across all PHP workers (unlike APCu,
        // which is per-process). Big speedup on ParserOutput hits because every
        // worker reuses the same parsed page tree.
        $wgObjectCaches['redis'] = [
            'class'      => 'RedisBagOStuff',
            'servers'    => [ getenv( 'REDIS_HOST' ) . ':6379' ],
            'persistent' => true,
        ];
        $wgMainCacheType    = 'redis';
        $wgParserCacheType  = 'redis';
        $wgMessageCacheType = 'redis';
        $wgSessionCacheType = 'redis';
    } else {
        // Fallback for environments without Redis available.
        $wgMainCacheType   = CACHE_ACCEL;
        $wgParserCacheType = CACHE_ACCEL;
    }
    $wgCacheDirectory = "/tmp"; // Use local tmp dir for cache if needed
    
    // Resource paths
    $wgLoadScript = 'https://wiki7.co.il/load.php';
    $wgExtensionAssetsPath = 'https://wiki7.co.il/extensions';
    $wgResourceBasePath = $wgScriptPath;
    
    // Logging
    $wgDebugLogGroups['FileOperation'] = 'php://stderr'; // Log file operations to stderr
    
    // S3 for file storage - this requires AWS extension to be installed
    if (getenv('S3_BUCKET_NAME')) {
        # Load AWS extension
        wfLoadExtension( 'AWS' );

        # Credentials come from the EC2 instance role via IMDSv2 (no explicit $wgAWSCredentials).
        # The AWS SDK PHP credential provider chain auto-discovers in this order:
        #   ECS task role → EC2 instance metadata → env vars → ~/.aws/credentials
        # Override only if explicit access keys are present in the environment (e.g. local dev).
        if (getenv('AWS_ACCESS_KEY_ID') && getenv('AWS_SECRET_ACCESS_KEY')) {
            $wgAWSCredentials = [
                'key'    => getenv('AWS_ACCESS_KEY_ID'),
                'secret' => getenv('AWS_SECRET_ACCESS_KEY'),
                'token'  => false,
            ];
        }

        # S3 configuration
        $wgAWSRegion = 'il-central-1';
        $wgAWSBucketName = getenv('S3_BUCKET_NAME');
        
        # This is the key setting that fixes the regional endpoint issue
        # It tells MediaWiki to serve files through your CloudFront/custom domain
        $wgAWSBucketDomain = 'https://wiki7.co.il';

        # Subdirectory within the bucket where files are stored
        $wgAWSBucketTopSubdirectory = "/images";
        
        # Set paths for direct S3 access (fallback if CloudFront is unavailable)
        $wgUploadPath = 'https://' . $wgAWSBucketName . '.s3.il-central-1.amazonaws.com/images';

        # You can add CloudWatch logging for S3 operations if needed
        # $wgAWSLogging = true;
    } else {
        # Fall back to local file system if S3 bucket name is not provided
        $wgUploadDirectory = '/var/www/html/images';
        $wgUploadPath = 'https://wiki7.co.il/images';
        $wgStylePath = 'https://wiki7.co.il/skins';
    }
} else {
    // Development mode
    $wgServer = "http://localhost:8080";
    
    // Error handling - verbose in development
    $wgShowExceptionDetails = true; // Show full error stack traces
    $wgShowDBErrorBacktrace = true; // Show DB error backtraces
    $wgDebugToolbar = true; // Enable debug toolbar in UI
    $wgDevelopmentWarnings = true; // Show PHP notices
    
    // Caching - disabled in development for easier debugging
    $wgCachePages = false; // Disable page caching for live changes
    $wgEnableParserCache = false; // Disable parsed output cache
    $wgMainCacheType = CACHE_NONE; // No object caching
    $wgParserCacheType = CACHE_NONE;
    $wgCacheDirectory = false; // Disable file cache
    
    // Logging
    $wgDebugLogFile = "/tmp/mediawiki-debug.log"; // Log debug to file
    
    // Local file storage in development
    $wgUploadDirectory = '/var/www/html/images';
    $wgUploadPath = '/images';

    // Resource loader debug
    $wgResourceLoaderDebug = true;
}

# --- End of environment-specific settings ---